// Generated by CoffeeScript 1.11.1
Ext.define('FM.model.Connection', {
  extend: 'Ext.data.Model',
  fields: [
    {
      name: "id",
      useNull: true
    }, {
      name: "host"
    }, {
      name: "port"
    }, {
      name: "user"
    }, {
      name: "decryptedPassword"
    }, {
      name: "type"
    }
  ],
  initConneciton: function(panel) {
    FM.Logger.debug('Connection initConnection() choosing...', arguments);
    if (this.get('type') === 'sftp') {
      FM.Logger.debug('Connection initConnection() SFTP called', arguments);
      FM.Actions.OpenRemoteConnection.execute(panel, {
        type: FM.Session.SFTP,
        path: '.',
        server_id: this.get('id')
      });
    }
    if (this.get('type') === 'ftp' || this.get('type') === '') {
      FM.Logger.debug('Connection initConnection() FTP called', arguments);
      return FM.Actions.OpenRemoteConnection.execute(panel, {
        type: FM.Session.FTP,
        path: '/',
        server_id: this.get('id')
      });
    }
  }
});
