// Generated by CoffeeScript 1.9.3
Ext.define('FM.model.FtpConnection', {
  extend: 'Ext.data.Model',
  fields: [
    {
      name: "id",
      useNull: true
    }, {
      name: "host"
    }, {
      name: "user"
    }, {
      name: "decryptedPassword"
    }
  ],
  initConneciton: function(panel) {
    FM.Logger.debug('FtpConnection initConnection() called', arguments);
    return FM.Actions.OpenFtp.execute(panel, {
      type: FM.Session.PUBLIC_FTP,
      path: '/',
      server_id: this.get('id')
    });
  }
});
