// Generated by CoffeeScript 1.9.3
Ext.define('FM.model.Site', {
  extend: 'Ext.data.Model',
  fields: [
    {
      name: "id",
      useNull: true
    }, {
      name: "domain"
    }, {
      name: "path"
    }, {
      name: "isolated"
    }
  ]
});
