// Generated by CoffeeScript 1.9.3
Ext.define('FM.view.windows.SuccessWindow', {
  extend: 'Ext.window.Window',
  alias: 'widget.success-window',
  cls: 'fm-success-window',
  layout: {
    type: 'vbox',
    align: 'center'
  },
  width: 300,
  resizable: false,
  initComponent: function(config) {
    var bottomTb;
    FM.Logger.log('FM.view.windows.SuccessWindow init');
    this.items = [];
    this.items.push({
      xtype: 'container',
      cls: 'fm-msg-success',
      height: 42,
      width: 42,
      margin: '15 0 10 0'
    });
    if (this.msg != null) {
      this.items.push({
        xtype: 'container',
        margin: 0,
        padding: '0 15',
        layout: {
          type: 'vbox',
          align: 'center'
        },
        items: [
          {
            xtype: 'displayfield',
            fieldLabel: this.msg,
            labelStyle: 'text-align: center; padding-bottom: 10px;',
            labelWidth: 260
          }
        ]
      });
    }
    bottomTb = new Ext.toolbar.Toolbar({
      ui: 'footer',
      dock: 'bottom',
      layout: {
        pack: 'center'
      },
      padding: '0 8 10 16',
      items: [
        {
          handler: (function(_this) {
            return function() {
              _this.close();
              if (_this.btnCallback != null) {
                return _this.btnCallback();
              }
            };
          })(this),
          scope: this,
          text: t("OK"),
          minWidth: 75
        }
      ]
    });
    this.dockedItems = [bottomTb];
    return this.callParent(arguments);
  }
});
