// Generated by CoffeeScript 1.9.3
(function() {
  Ext.define('FM.view.windows.TerminalWindow', {
    extend: 'Ext.ux.window.Window',
    alias: 'widget.terminal-window',
    cls: 'fm-terminal-window',
    layout: "fit",
    constrain: true,
    animate: true,
    maximizable: true,
    border: false,
    width: 700,
    height: 500,
    margin: 0,
    listeners: {
      beforeshow: {
        fn: function() {
          return FM.Logger.debug('FM.view.windows.TerminalWindow beforeshow() called', this, arguments);
        }
      },
      beforeclose: {
        fn: function(editor_window) {
          FM.Logger.debug('FM.view.windows.TerminalWindow beforeclose() called', this, arguments);
          return true;
        }
      }
    },
    initComponent: function() {
      FM.Logger.log('FM.view.windows.Terminal initComponent() called', arguments);
      this.items = [];
      this.items.push({
        frame: false,
        border: false,
        xtype: "component",
        autoEl: {
          tag: "iframe",
          src: this.address,
          frameborder: 0
        }
      });
      return this.callParent(arguments);
    },
    exit: function() {
      FM.Logger.debug('FM.view.windows.TerminalWindow exit() called', arguments);
      return this.close();
    }
  });

}).call(this);
