// Generated by CoffeeScript 1.9.3
(function() {
  Ext.define('FM.view.windows.TerminalWindow', {
    extend: 'Ext.ux.window.Window',
    alias: 'widget.terminal-window',
    cls: 'fm-terminal-window',
    layout: "fit",
    constrain: true,
    animate: true,
    maximizable: true,
    border: false,
    width: 700,
    height: 600,
    margin: 0,
    items: [
      {
        id: "idTerm",
        frame: false,
        border: false,
        xtype: "component",
        autoEl: {
          id: "idTerminal",
          tag: "iframe",
          src: "https://localhost:3000",
          frameborder: 0
        }
      }
    ],
    listeners: {
      beforeshow: {
        fn: function() {
          return FM.Logger.debug('FM.view.windows.TerminalWindow beforeshow() called', this, arguments);
        }
      },
      beforeclose: {
        fn: function(editor_window) {
          FM.Logger.debug('FM.view.windows.TerminalWindow beforeclose() called', this, arguments);
          return true;
        }
      }
    },
    initComponent: function() {
      FM.Logger.debug('FM.view.windows.Terminal initComponent() called', arguments);
      return this.callParent(arguments);
    },
    setCredentials: function(host, user) {
      var pattern;
      pattern = function(arg) {
        var host, user;
        user = arg.user, host = arg.host;
        return "https://localhost:3000/wetty/ssh/" + user + "/" + host;
      };
      return Ext.get('idTerm').dom.src = pattern({
        user: user,
        host: host
      });
    },
    exit: function() {
      FM.Logger.debug('FM.view.windows.TerminalWindow exit() called', arguments);
      return this.close();
    }
  });

}).call(this);
