// Generated by CoffeeScript 1.9.3
Ext.define('FM.view.toolbars.FileListBottomToolbar', {
  extend: 'Ext.toolbar.Toolbar',
  alias: 'widget.file-list-bottom-toolbar',
  cls: 'fm-file-list-bottom-toolbar',
  items: [],
  requires: ['FM.view.toolbars.FileListStatusBar', 'FM.view.toolbars.FileListServerBar', 'FM.view.toolbars.FileListSizeBar'],
  initComponent: function() {
    FM.Logger.log('FM.view.toolbars.FileListBottomToolbar init');
    this.items = [];
    this.items.push({
      xtype: 'file-list-status-bar'
    });
    this.items.push("->");
    this.items.push({
      xtype: 'file-list-server-bar'
    });
    this.items.push({
      xtype: 'file-list-size-bar'
    });
    return this.callParent(arguments);
  }
});
