// Generated by CoffeeScript 1.11.1
Ext.define('FM.view.toolbars.FileListServerBar', {
  extend: 'Ext.toolbar.TextItem',
  alias: 'widget.file-list-server-bar',
  cls: 'fm-serverbar',
  initComponent: function() {
    FM.Logger.log('FM.view.toolbars.FileListServerBar init');
    return this.callParent(arguments);
  }
});
