// Generated by CoffeeScript 1.11.1
Ext.define('FM.view.toolbars.FileListStatusBar', {
  extend: 'Ext.toolbar.TextItem',
  alias: 'widget.file-list-status-bar',
  cls: 'fm-serverbar',
  initComponent: function() {
    FM.Logger.log('FM.view.toolbars.FileListStatusBar init');
    this.text = t("Loading...");
    return this.callParent(arguments);
  }
});
