// Generated by CoffeeScript 1.11.1
Ext.define('FM.view.toolbars.FileListPathBar', {
  extend: 'Ext.toolbar.TextItem',
  alias: 'widget.file-list-path-bar',
  cls: 'fm-pathbar',
  initComponent: function() {
    FM.Logger.log('FM.view.toolbars.FileListPathBar init');
    return this.callParent(arguments);
  }
});
