// Generated by CoffeeScript 1.11.1
Ext.define('FM.action.CopyEntry', {
  extend: 'FM.overrides.Action',
  config: {
    iconCls: "fm-action-copy-entry",
    text: t("Current File"),
    handler: function(panel) {
      var record;
      if (panel == null) {
        panel = FM.Active;
      }
      FM.Logger.info('Run Action FM.action.CopyEntry', arguments);
      record = FM.helpers.GetLastSelected(panel);
      if ((record != null) && record.get('name') !== '..') {
        return FM.helpers.CopyToClipboard(record.get('name'));
      } else {
        return FM.helpers.ShowError(t("Please select file entry."));
      }
    }
  }
});
