// Generated by CoffeeScript 1.9.3
Ext.define('FM.action.CopyPath', {
  extend: 'FM.overrides.Action',
  config: {
    iconCls: "fm-action-copy-path",
    text: t("Current Path"),
    handler: function(panel) {
      var record;
      if (panel == null) {
        panel = FM.Active;
      }
      FM.Logger.info('Run Action FM.action.CopyPath', arguments);
      record = FM.helpers.GetLastSelected(panel);
      if (record) {
        if (record.get('name') === '..') {
          return FM.helpers.CopyToClipboard(panel.session.path);
        } else {
          return FM.helpers.CopyToClipboard(FM.helpers.GetAbsName(panel.session, record));
        }
      } else {
        return FM.helpers.CopyToClipboard(panel.session.path);
      }
    }
  }
});
