// Generated by CoffeeScript 1.11.1
Ext.define('FM.action.DownloadArchive', {
  extend: 'FM.overrides.Action',
  requires: ['FM.action.DownloadZip'],
  config: {
    scale: "large",
    iconAlign: "top",
    iconCls: "fm-action-download-archive",
    text: t("Download Archive"),
    handler: function(panel, records) {
      FM.Logger.info('Run Action FM.action.DownloadArchive', arguments);
      return FM.Actions.DownloadZip.execute(panel, records);
    }
  }
});
