// Generated by CoffeeScript 1.11.1
Ext.define('FM.action.DownloadBasic', {
  extend: 'FM.overrides.Action',
  requires: ['Ext.form.action.StandardSubmit'],
  config: {
    iconCls: "fm-action-download-basic",
    text: t("Basic Download (file)"),
    handler: function(panel, record) {
      var path, session;
      FM.Logger.info('Run Action FM.action.DownloadBasic', arguments);
      if ((record == null) || record.get('is_dir')) {
        FM.helpers.ShowError(t("Please select file(not a directory) entry."));
        return;
      }
      session = Ext.ux.Util.clone(panel.session);
      path = FM.helpers.GetAbsName(session, record);
      return FM.backend.ajaxSubmit('/actions/files/download', {
        params: {
          session: Ext.JSON.encode(session),
          mode: 'default',
          paths: Ext.JSON.encode([path])
        }
      });
    }
  }
});
