// Generated by CoffeeScript 1.9.3
Ext.define('FM.action.Help', {
  extend: 'FM.overrides.Action',
  config: {
    iconCls: "fm-action-help",
    text: t("Help"),
    handler: function() {
      FM.Logger.info('Run Action FM.action.Help', arguments);
      return window.open('http://beget.ru/man_filem', '_blank');
    }
  }
});
