// Generated by CoffeeScript 1.11.1
Ext.define('FM.action.Local', {
  extend: 'FM.overrides.Action',
  config: {
    scale: "large",
    iconAlign: "top",
    iconCls: "fm-action-local",
    text: t("My Computer"),
    handler: function(panel) {
      FM.Logger.debug('Run Action FM.action.Local', arguments, panel.toString());
      if (panel.toString() === 'Right') {
        panel.applet = Ext.getElementById('applet_right');
      } else {
        panel.applet = Ext.getElementById('applet_left');
      }
      return panel.applet.start(panel.toString());
    }
  }
});
