// Generated by CoffeeScript 1.9.3
Ext.define('FM.action.Logout', {
  extend: 'FM.overrides.Action',
  config: {
    iconCls: "fm-action-logout",
    text: t("Logout"),
    handler: function() {
      FM.Logger.info('Run Action FM.action.Logout', arguments);
      return FM.backend.ajaxSend('/actions/main/logout', {
        success: function() {
          return location.reload();
        },
        failure: function(response) {
          FM.Logger.debug(response);
          FM.helpers.ShowError(t("Error during logout. Please contact Support."));
          return FM.Logger.error(response);
        }
      });
    }
  }
});
