// Generated by CoffeeScript 1.9.3
Ext.define('FM.action.Navigate', {
  extend: 'FM.overrides.Action',
  config: {
    iconCls: "fm-action-navigate",
    text: t("Navigate"),
    handler: function() {
      var promt;
      FM.Logger.info('Run Action FM.action.Navigate', arguments);
      promt = Ext.create('FM.view.windows.PromtWindow', {
        title: t("Navigate"),
        msg: t("Enter path to navigate:"),
        fieldValue: FM.Active.session.path,
        ok: function(button, promt_window, field) {
          var path;
          FM.Logger.debug('ok handler()', arguments);
          path = field.getValue();
          FM.Actions.Open.execute(FM.Active, path);
          return promt_window.close();
        }
      });
      return promt.show();
    }
  }
});
